/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.tech9.telas;

import br.com.tech9.dal.SistemaDao;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

/**
 *
 * @author felip
 */
public class CadProd extends javax.swing.JFrame {

    /**
     * Creates new form CadProd
     */
    public CadProd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtValor = new javax.swing.JTextField();
        txtIdProd = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        txtNomeProd = new javax.swing.JTextField();
        lblFundo = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setTitle("Cadastro de produtos");
        setResizable(false);
        getContentPane().setLayout(null);

        txtValor.setBackground(new java.awt.Color(255, 255, 255));
        txtValor.setBorder(null);
        getContentPane().add(txtValor);
        txtValor.setBounds(60, 130, 180, 28);

        txtIdProd.setBackground(new java.awt.Color(255, 255, 255));
        txtIdProd.setBorder(null);
        getContentPane().add(txtIdProd);
        txtIdProd.setBounds(60, 30, 180, 28);

        txtQuantidade.setBackground(new java.awt.Color(255, 255, 255));
        txtQuantidade.setBorder(null);
        getContentPane().add(txtQuantidade);
        txtQuantidade.setBounds(60, 178, 180, 30);

        txtNomeProd.setBackground(new java.awt.Color(255, 255, 255));
        txtNomeProd.setBorder(null);
        getContentPane().add(txtNomeProd);
        txtNomeProd.setBounds(60, 80, 180, 28);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/tech9/icones/Cadastro ProdutoTrue.png"))); // NOI18N
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 0, 610, 320);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(310, 60, 83, 28);

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(310, 90, 63, 28);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(310, 130, 64, 28);

        setSize(new java.awt.Dimension(624, 360));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
         String id, n, q, p;
        id = txtIdProd.getText();
        n = txtNomeProd.getText();
        q = txtQuantidade.getText();
        p = txtValor.getText();
        if (id.isEmpty()) { // se usuário está vazio
            JOptionPane.showMessageDialog(null, "É obrigatório digitar o Id do produto");
            txtIdProd.requestFocus();
            return; // stop
        }
        if (n.isEmpty()) { // se senha está vazia
            JOptionPane.showMessageDialog(null, "É obrigatório digitar o nome do produto");
            txtNomeProd.requestFocus();
            return; // stop
        }
        try {
            //Salvar os dados do usuário
            SistemaDao dao;
            dao = new SistemaDao();
            dao.salvarProduto(id,n,q,p);

            //4.1 Mostrar a mensagem "Usuário salvo com sucesso" e limpar os campos.
            JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso");
            txtIdProd.setText("");
            txtNomeProd.setText("");
            txtQuantidade.setText(""); 
            txtValor.setText("");
            txtIdProd.requestFocus();

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Mensagem de erro:" + ex.getMessage());
        } 
        catch (SQLException ex) {
            int erro = ex.getErrorCode();
            if (erro == 1062) {
                JOptionPane.showMessageDialog(null, "Usuário Já cadastrado");
                txtIdProd.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "ENtre em contato com o administrador do sistema e informe o erro: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int resposta; // 0 - Sim; 1 - Não 
        resposta = JOptionPane.showConfirmDialog(null, "Confirma?", "Confirmação", 0);
        //1.1 - Se a responta for sim
        if (resposta == 0) { //Resposta SIM
            //1.1.1 Obter o usuário no txtUsuario.
            String u = txtIdProd.getText();

            try {
                //Excluir o usuário
                SistemaDao dao;
                dao = new SistemaDao();
                dao.excluirProduto(u);

                //1.1.4 Mostrar a mensagem "Usuário excluído com sucesso" e limpar os campos.
                JOptionPane.showMessageDialog(null, "Produto excluído com sucesso");
                //1.1.5 Fecha a TelaUsuario 
                dispose();

            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, "Mensagem de erro:" + ex.getMessage());
            }
            //1.2 - Se a resposta for não
            //1.2.2 Fecha a TelaUsuario  
        } else {
            dispose();
        }
       
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        abrirTelaProduto();
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadProd().setVisible(true);
            }
        });
        
    }
     private void abrirTelaProduto(){
        // 1 - Solicitar o usuário
        String p = JOptionPane.showInputDialog("Qual o ID do produto que voce deseja?");
        if(p == null){
            return; //stop
        }
        try {
             SistemaDao dao;
             dao = new SistemaDao();
             ResultSet resultado;
             resultado = dao.buscarProduto(p);

            //4 - Verificar se o usuário foi encontrado na tabela usuario do banco de dados.
            if (resultado.next()) {
                //Pega o nome e o cargo que veio na consulta ao banco de dados
                String idProd, nome, preco, quantidade;
                idProd = resultado.getString("idproduto");
                nome = resultado.getString("nome");
                preco = resultado.getString("preco");
                quantidade = resultado.getString("quantidade");
                //Abrir o formulário Menu.java
                this.dispose();
                Alterar alterar;
                alterar = new Alterar(idProd, nome, preco, quantidade);
                alterar.setVisible(true);
                
            } else {
                JOptionPane.showMessageDialog(null, "Produto não encontrado");
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Driver não está na library");
        } 
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Você errou nos dados da conexão com o banco de dados");
        }
     }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JTextField txtIdProd;
    private javax.swing.JTextField txtNomeProd;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
