/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.tech9.telas;

import br.com.tech9.dal.SistemaDao;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

/**
 *
 * @author felip
 */
public class CadUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CadUsuario
     */
    public CadUsuario() {
        initComponents();
        
    }
    public CadUsuario(String usuario, String senha, String nome, String cargo) {
        initComponents();
        txtUsuario.setText(usuario);
        txtSenha.setText(senha);
        txtNome.setText(nome);
        cmbCargo.setSelectedItem(cargo);
        btnExcluir.setVisible(true);
        lblEsconde.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEsconde = new javax.swing.JLabel();
        cmbCargo = new javax.swing.JComboBox<>();
        txtNome = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        lblFundo = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();

        setTitle("Cadastro de usuarios");
        setResizable(false);
        getContentPane().setLayout(null);

        lblEsconde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/tech9/icones/fundogenerico.png"))); // NOI18N
        getContentPane().add(lblEsconde);
        lblEsconde.setBounds(300, 146, 90, 30);

        cmbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "usuario" }));
        getContentPane().add(cmbCargo);
        cmbCargo.setBounds(60, 200, 180, 26);

        txtNome.setAlignmentX(0.3F);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(60, 110, 190, 30);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(60, 160, 190, 30);
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(60, 60, 190, 28);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/tech9/icones/Cadastrotrue.png"))); // NOI18N
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 0, 650, 370);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(310, 80, 83, 28);

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(310, 150, 64, 28);

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(310, 120, 63, 28);

        setSize(new java.awt.Dimension(593, 370));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
         //1 - Pegar as informações dos campos do formulário.
        String u, s, n, c;
        u = txtUsuario.getText();
        s = txtSenha.getText();
        n = txtNome.getText();
        c = cmbCargo.getSelectedItem().toString();
        //2 - Verificar se os campos txtUsuario e txtSenha do formulário, não estão vazios.
        if (u.isEmpty()) { // se usuário está vazio
            JOptionPane.showMessageDialog(null, "É obrigatório digitar o usuário");
            txtUsuario.requestFocus();
            return; // stop
        }
        if (s.isEmpty()) { // se senha está vazia
            JOptionPane.showMessageDialog(null, "É obrigatório digitar a senha");
            txtSenha.requestFocus();
            return; // stop
        }

        try {
            //Salvar os dados do usuário
            SistemaDao dao;
            dao = new SistemaDao();
            dao.salvarUsuario(u, n, s, c);

            //4.1 Mostrar a mensagem "Usuário salvo com sucesso" e limpar os campos.
            JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso");
            txtUsuario.setText("");
            txtSenha.setText("");
            txtNome.setText("");
            cmbCargo.setSelectedIndex(0);
            txtUsuario.requestFocus();

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Mensagem de erro:" + ex.getMessage());
        }
        catch (SQLException ex) {
            int erro = ex.getErrorCode();
            if (erro == 1062) {
                JOptionPane.showMessageDialog(null, "Usuário Já cadastrado");
                txtUsuario.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "ENtre em contato com o administrador do sistema e informe o erro: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        abrirTelaAlterar();
       
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int resposta; // 0 - Sim; 1 - Não 
        resposta = JOptionPane.showConfirmDialog(null, "Confirma?", "Confirmação", 0);
        //1.1 - Se a responta for sim
        if (resposta == 0) { //Resposta SIM
            //1.1.1 Obter o usuário no txtUsuario.
            String u = txtUsuario.getText();

            try {
                //Excluir o usuário
                SistemaDao dao;
                dao = new SistemaDao();
                dao.excluirUsuario(u);

                //1.1.4 Mostrar a mensagem "Usuário excluído com sucesso" e limpar os campos.
                JOptionPane.showMessageDialog(null, "Usuário excluído com sucesso");
                //1.1.5 Fecha a TelaUsuario 
                dispose();

            } 
            catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, "Mensagem de erro:" + ex.getMessage());
            }
            //1.2 - Se a resposta for não
            //1.2.2 Fecha a TelaUsuario  
        } else {
            dispose();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadUsuario().setVisible(true);
            }
        });
    }
        private void abrirTelaAlterar(){
        // 1 - Solicitar o usuário
        String p = JOptionPane.showInputDialog("Qual o usuario deseja alterar?");
        if(p == null){
            return; //stop
        }
        try {
             SistemaDao dao;
             dao = new SistemaDao();
             ResultSet resultado;
             resultado = dao.buscarUsuario(p);

            //4 - Verificar se o usuário foi encontrado na tabela usuario do banco de dados.
            if (resultado.next()) {
                //Pega o nome e o cargo que veio na consulta ao banco de dados
                String usuario, nome, senha,cargo;
                usuario = resultado.getString("usuario");
                senha = resultado.getString("senha");
                nome = resultado.getString("nome");
                cargo = resultado.getString("cargo");
                //Abrir o formulário Menu.java
                this.hide();
                AlterarUsuario alterar;
                alterar = new AlterarUsuario(usuario, senha, nome, cargo);
                alterar.setVisible(true);
                
            } else {
                JOptionPane.showMessageDialog(null, "Produto não encontrado");
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Driver não está na library");
        } 
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Você errou nos dados da conexão com o banco de dados");
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JComboBox<String> cmbCargo;
    private javax.swing.JLabel lblEsconde;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
