/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.tech9.telas;

import br.com.tech9.dal.SistemaDao;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author felip
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial(String usuario, String cargo) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnAjuda = new javax.swing.JButton();
        lblFundoInicio = new javax.swing.JLabel();
        btnAdcProd = new javax.swing.JButton();
        btnEstoque = new javax.swing.JButton();
        btnDeletarProd = new javax.swing.JButton();
        btnNovoUsuario = new javax.swing.JButton();
        btnAlterarUsuario = new javax.swing.JButton();
        btnDeletarUsuario = new javax.swing.JButton();
        lblMural = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIstema De Controle Tech9");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ola,");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 22, 16);

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Hoje é dia :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 0, 100, 16);

        lblUsuario.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(51, 51, 51));
        lblUsuario.setText("Usuario");
        getContentPane().add(lblUsuario);
        lblUsuario.setBounds(40, 0, 140, 16);

        lblData.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblData.setForeground(new java.awt.Color(0, 0, 0));
        lblData.setText("Data");
        getContentPane().add(lblData);
        lblData.setBounds(290, 0, 80, 16);

        btnSair.setBackground(new java.awt.Color(204, 0, 51));
        btnSair.setForeground(new java.awt.Color(0, 0, 0));
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(500, 0, 50, 20);

        btnAjuda.setBackground(new java.awt.Color(0, 102, 102));
        btnAjuda.setText("Ajuda");
        btnAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjudaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAjuda);
        btnAjuda.setBounds(490, 340, 59, 20);

        lblFundoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/tech9/icones/Home4.png"))); // NOI18N
        lblFundoInicio.setText("Ola");
        getContentPane().add(lblFundoInicio);
        lblFundoInicio.setBounds(0, -20, 640, 420);

        btnAdcProd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdcProd.setText("jButton1");
        btnAdcProd.setBorder(null);
        btnAdcProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdcProdActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdcProd);
        btnAdcProd.setBounds(130, 38, 100, 40);

        btnEstoque.setBackground(new java.awt.Color(255, 255, 255));
        btnEstoque.setText("jButton2");
        btnEstoque.setBorder(null);
        btnEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstoqueActionPerformed(evt);
            }
        });
        getContentPane().add(btnEstoque);
        btnEstoque.setBounds(130, 120, 100, 50);

        btnDeletarProd.setBackground(new java.awt.Color(255, 255, 255));
        btnDeletarProd.setText("jButton3");
        btnDeletarProd.setBorder(null);
        btnDeletarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarProdActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletarProd);
        btnDeletarProd.setBounds(130, 210, 100, 40);

        btnNovoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        btnNovoUsuario.setText("jButton1");
        btnNovoUsuario.setBorder(null);
        btnNovoUsuario.setBorderPainted(false);
        btnNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovoUsuario);
        btnNovoUsuario.setBounds(253, 38, 110, 40);

        btnAlterarUsuario.setBackground(new java.awt.Color(255, 255, 255));
        btnAlterarUsuario.setText("jButton2");
        btnAlterarUsuario.setBorder(null);
        btnAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterarUsuario);
        btnAlterarUsuario.setBounds(260, 120, 100, 50);

        btnDeletarUsuario.setBackground(new java.awt.Color(255, 255, 255));
        btnDeletarUsuario.setText("jButton3");
        btnDeletarUsuario.setBorder(null);
        btnDeletarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletarUsuario);
        btnDeletarUsuario.setBounds(250, 210, 110, 40);

        lblMural.setText("jLabel1");
        getContentPane().add(lblMural);
        lblMural.setBounds(380, 40, 110, 260);

        setSize(new java.awt.Dimension(566, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoUsuarioActionPerformed
        CadUsuario cadastro;
        cadastro = new CadUsuario();
        cadastro.setVisible(true);
    }//GEN-LAST:event_btnNovoUsuarioActionPerformed

    private void btnAdcProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdcProdActionPerformed
        CadProd cadastro;
        cadastro = new CadProd();
        cadastro.setVisible(true);
    }//GEN-LAST:event_btnAdcProdActionPerformed

    private void btnDeletarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarProdActionPerformed
        CadProd cadastro;
        cadastro = new CadProd();
        cadastro.setVisible(true);
    }//GEN-LAST:event_btnDeletarProdActionPerformed

    private void btnDeletarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarUsuarioActionPerformed
        abrirTelaExcluir();
    }//GEN-LAST:event_btnDeletarUsuarioActionPerformed

    private void btnAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarUsuarioActionPerformed
        abrirTelaAlterar();
    }//GEN-LAST:event_btnAlterarUsuarioActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // substituir a lbl pela data atual do sistema
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lblData.setText(formatador.format(data));
        
    }//GEN-LAST:event_formWindowActivated

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?","Atenção",JOptionPane.YES_NO_OPTION);
        if (sair == 0) {
        System.exit(0);
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjudaActionPerformed
        Sobre sobre = new Sobre();
        sobre.setVisible(true);
    }//GEN-LAST:event_btnAjudaActionPerformed

    private void btnEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueActionPerformed
          Estoque estoque = new Estoque();
          estoque.setVisible(true);
    }//GEN-LAST:event_btnEstoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }
        private void abrirTelaAlterar(){
        // 1 - Solicitar o usuário
        String p = JOptionPane.showInputDialog("Qual o usuario deseja alterar?");
        if(p == null){
            return; //stop
        }
        try {
             SistemaDao dao;
             dao = new SistemaDao();
             ResultSet resultado;
             resultado = dao.buscarUsuario(p);

            //4 - Verificar se o usuário foi encontrado na tabela usuario do banco de dados.
            if (resultado.next()) {
                //Pega o nome e o cargo que veio na consulta ao banco de dados
                String usuario, nome, senha,cargo;
                usuario = resultado.getString("usuario");
                senha = resultado.getString("senha");
                nome = resultado.getString("nome");
                cargo = resultado.getString("cargo");
                //Abrir o formulário Menu.java
                this.dispose();
                AlterarUsuario alterar;
                alterar = new AlterarUsuario(usuario, senha, nome, cargo);
                alterar.setVisible(true);
                
            } else {
                JOptionPane.showMessageDialog(null, "Usuario não encontrado");
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Driver não está na library");
        } 
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Você errou nos dados da conexão com o banco de dados");
        }
        }
         private void abrirTelaExcluir(){
        // 1 - Solicitar o usuário
        String p = JOptionPane.showInputDialog("Qual o usuario deseja excluir?");
        if(p == null){
            return; //stop
        }
        try {
             SistemaDao dao;
             dao = new SistemaDao();
             ResultSet resultado;
             resultado = dao.buscarUsuario(p);

            //4 - Verificar se o usuário foi encontrado na tabela usuario do banco de dados.
            if (resultado.next()) {
                //Pega o nome e o cargo que veio na consulta ao banco de dados
                String usuario, nome, senha,cargo;
                usuario = resultado.getString("usuario");
                senha = resultado.getString("senha");
                nome = resultado.getString("nome");
                cargo = resultado.getString("cargo");
                //Abrir o formulário Menu.java
                this.dispose();
                CadUsuario cadastro;
                cadastro = new CadUsuario(usuario, senha, nome, cargo);
                cadastro.setVisible(true);
                
            } else {
                JOptionPane.showMessageDialog(null, "Usuario não encontrado");
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Driver não está na library");
        } 
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Você errou nos dados da conexão com o banco de dados");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdcProd;
    private javax.swing.JButton btnAjuda;
    private javax.swing.JButton btnAlterarUsuario;
    private javax.swing.JButton btnDeletarProd;
    private javax.swing.JButton btnDeletarUsuario;
    private javax.swing.JButton btnEstoque;
    private javax.swing.JButton btnNovoUsuario;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblFundoInicio;
    private javax.swing.JLabel lblMural;
    public static javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
